// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk-ACnCKv7biGHe6fUZlSXekQpz_uckKk',
    appId: '1:368682073122:web:1dd0e1ba2d025a73c31e7b',
    messagingSenderId: '368682073122',
    projectId: 'ecommerce-test-54853',
    authDomain: 'ecommerce-test-54853.firebaseapp.com',
    storageBucket: 'ecommerce-test-54853.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_2unNysO0iunwVI1u1piMntJcqORGLs8',
    appId: '1:368682073122:android:eef0a60311fc896ac31e7b',
    messagingSenderId: '368682073122',
    projectId: 'ecommerce-test-54853',
    storageBucket: 'ecommerce-test-54853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo-zInUCkIdnlVr7rTyxWXeM-uHkHaglk',
    appId: '1:368682073122:ios:2a0562f70f342e7dc31e7b',
    messagingSenderId: '368682073122',
    projectId: 'ecommerce-test-54853',
    storageBucket: 'ecommerce-test-54853.firebasestorage.app',
    iosBundleId: 'com.example.eComAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo-zInUCkIdnlVr7rTyxWXeM-uHkHaglk',
    appId: '1:368682073122:ios:2a0562f70f342e7dc31e7b',
    messagingSenderId: '368682073122',
    projectId: 'ecommerce-test-54853',
    storageBucket: 'ecommerce-test-54853.firebasestorage.app',
    iosBundleId: 'com.example.eComAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk-ACnCKv7biGHe6fUZlSXekQpz_uckKk',
    appId: '1:368682073122:web:b8f318b97ccdb4c4c31e7b',
    messagingSenderId: '368682073122',
    projectId: 'ecommerce-test-54853',
    authDomain: 'ecommerce-test-54853.firebaseapp.com',
    storageBucket: 'ecommerce-test-54853.firebasestorage.app',
  );
}
